server:
  port: 8082
spring:
  profiles:
    active: qa
---
spring:
  profiles: dev
  application:
    name: Sprint-boot-tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!

---
spring:
  profiles: qa
  application:
    name: Sprint-boot-tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to qa Daily Code Buffer!!

---

spring:
  profiles: dev
  application:
    name: Sprint-boot-tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to prod Daily Code Buffer!!

# Uncomment the following for H2 Database configuration
# spring:
#   h2:
#     console:
#       enabled: true
#   datasource:
#     url: jdbc:h2:mem:dcbapp
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: password
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
